//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetHouse_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int IdApplication { get; set; }
        public int IdManager { get; set; }
    
        public virtual ApplicationSet ApplicationSet { get; set; }
        public virtual ManagerSet ManagerSet { get; set; }
    }
}
